`timescale 1ns / 1ps
//============================================================================
// Testbench for 2D CNN (parallel-filter conv_pool_2d + sequential FC via layer_seq)
//
// Architecture: Conv2D_1(1→4, 3×3) → Pool2D(2×2) → Conv2D_2(4→8, 3×3)
//               → Pool2D(2×2) → FC1(200→32) → FC2(32→10)
//
// Conv layers process all output filters in parallel (OUT_CH multipliers).
// Loads .mem files generated by cnn2d_model.py, runs inference, reports result.
//============================================================================
module tb_cnn2d;

    // ---- Architecture parameters (must match cnn2d_top) ----
    parameter INPUT_H       = 28;
    parameter INPUT_W       = 28;
    parameter INPUT_CH      = 1;

    parameter CONV1_OUT_CH  = 4;
    parameter CONV1_KERNEL  = 3;
    parameter CONV1_OUT_H   = INPUT_H - CONV1_KERNEL + 1;  // 26
    parameter CONV1_OUT_W   = INPUT_W - CONV1_KERNEL + 1;  // 26

    parameter POOL1_SIZE    = 2;
    parameter POOL1_OUT_H   = CONV1_OUT_H / POOL1_SIZE;    // 13
    parameter POOL1_OUT_W   = CONV1_OUT_W / POOL1_SIZE;    // 13

    parameter CONV2_IN_CH   = CONV1_OUT_CH;                 // 4
    parameter CONV2_OUT_CH  = 8;
    parameter CONV2_KERNEL  = 3;
    parameter CONV2_OUT_H   = POOL1_OUT_H - CONV2_KERNEL + 1;  // 11
    parameter CONV2_OUT_W   = POOL1_OUT_W - CONV2_KERNEL + 1;  // 11

    parameter POOL2_SIZE    = 2;
    parameter POOL2_OUT_H   = CONV2_OUT_H / POOL2_SIZE;    // 5
    parameter POOL2_OUT_W   = CONV2_OUT_W / POOL2_SIZE;    // 5

    parameter FLATTEN_SIZE  = POOL2_OUT_H * POOL2_OUT_W * CONV2_OUT_CH;  // 200
    parameter FC1_OUT       = 32;
    parameter FC2_OUT       = 10;
    parameter PAD           = 20;

    parameter FC1_WIDTH       = PAD + FLATTEN_SIZE + PAD - 1;  // 239
    parameter FC2_WIDTH       = PAD + FC1_OUT + PAD - 1;       // 71

    parameter BITS         = 31;
    localparam OUTPUT_BITS = BITS + 8 + 8;  // Two FC layers add 8 bits each

    // Timing — parallel-filter conv ~20K + sequential FC ~8.6K = ~29K cycles
    parameter CLK_PERIOD_NS   = 10;
    parameter SIM_DURATION_NS = 500000;   // 0.5 ms — generous for ~29K cycle design

    // ---- DUT signals ----
    reg  clk;
    reg  rstn;

    // Input image — 28×28 = 784 Q16.16 values
    reg signed [31:0] data_in [0 : INPUT_H * INPUT_W * INPUT_CH - 1];

    // Conv2D weights & biases
    reg signed [31:0] conv1_w [0 : CONV1_OUT_CH * INPUT_CH * CONV1_KERNEL * CONV1_KERNEL - 1];
    reg signed [31:0] conv1_b [0 : CONV1_OUT_CH - 1];
    reg signed [31:0] conv2_w [0 : CONV2_OUT_CH * CONV2_IN_CH * CONV2_KERNEL * CONV2_KERNEL - 1];
    reg signed [31:0] conv2_b [0 : CONV2_OUT_CH - 1];

    // FC biases (weights now loaded internally by layer_seq from .mem files)
    reg signed [31:0] fc1_b [0 : FC1_OUT - 1];
    reg signed [31:0] fc2_b [0 : FC2_OUT - 1];

    // Output
    wire signed [BITS+16:0] cnn_out [0 : FC2_OUT - 1];

    // ---- DUT instantiation ----
    cnn2d_top #(
        .INPUT_H      (INPUT_H),
        .INPUT_W      (INPUT_W),
        .INPUT_CH     (INPUT_CH),
        .CONV1_OUT_CH (CONV1_OUT_CH),
        .CONV1_KERNEL (CONV1_KERNEL),
        .POOL1_SIZE   (POOL1_SIZE),
        .CONV2_IN_CH  (CONV2_IN_CH),
        .CONV2_OUT_CH (CONV2_OUT_CH),
        .CONV2_KERNEL (CONV2_KERNEL),
        .POOL2_SIZE   (POOL2_SIZE),
        .FC1_OUT      (FC1_OUT),
        .FC2_OUT      (FC2_OUT),
        .PAD          (PAD),
        .BITS         (BITS),
        .FC1_WEIGHT_FILE("fc1_w.mem"),
        .FC2_WEIGHT_FILE("fc2_w.mem")
    ) dut (
        .clk      (clk),
        .rstn     (rstn),
        .data_in  (data_in),
        .conv1_w  (conv1_w),
        .conv1_b  (conv1_b),
        .conv2_w  (conv2_w),
        .conv2_b  (conv2_b),
        .fc1_b    (fc1_b),
        .fc2_b    (fc2_b),
        .cnn_out  (cnn_out)
    );

    // ---- Clock ----
    initial clk = 1'b0;
    always #(CLK_PERIOD_NS / 2) clk = ~clk;

    // ---- Cycle counter ----
    integer cycle_count;
    always @(posedge clk or negedge rstn) begin
        if (!rstn)
            cycle_count <= 0;
        else
            cycle_count <= cycle_count + 1;
    end

    // ---- Per-layer cycle capture ----
    integer reset_cycle;
    integer conv1_pool1_cycle;
    integer conv2_pool2_cycle;
    integer fc1_cycle;
    integer fc2_cycle;

    // ---- One-shot flags (counter_donestatus toggles in S_DONE) ----
    reg fc1_done_seen;
    reg fc2_done_seen;
    initial begin fc1_done_seen = 0; fc2_done_seen = 0; end

    // ---- Argmax vars ----
    integer detected_digit;
    integer n;
    reg signed [BITS+16:0] max_val;

    // Expected label
    reg [31:0] expected_label_arr [0:0];
    integer    expected_label;

    // ---- Argmax task ----
    task find_predicted_digit;
        begin
            max_val = cnn_out[0];
            detected_digit = 0;
            for (n = 1; n < FC2_OUT; n = n + 1) begin
                if (cnn_out[n] > max_val) begin
                    max_val = cnn_out[n];
                    detected_digit = n;
                end
            end
        end
    endtask

    // ---- Display task ----
    task display_all_outputs;
        begin
            $display("============================================================");
            $display("  2D CNN OUTPUT VALUES  (Q16.16 raw logits)");
            $display("============================================================");
            for (n = 0; n < FC2_OUT; n = n + 1) begin
                $display("  Output[%0d] (digit %0d) = %0d", n, n, cnn_out[n]);
            end
            $display("============================================================");
        end
    endtask

    // ---- Main stimulus ----
    initial begin
        $display("\n============================================================");
        $display("  STANDARD 2D CNN TESTBENCH - LOADING DATA");
        $display("============================================================\n");

        // ---- Load conv2d weights ----
        $display("[INFO] Loading Conv1 weights (conv1_w.mem) — %0d entries ...",
                 CONV1_OUT_CH * INPUT_CH * CONV1_KERNEL * CONV1_KERNEL);
        $readmemh("conv1_w.mem", conv1_w);

        $display("[INFO] Loading Conv1 biases (conv1_b.mem) — %0d entries ...",
                 CONV1_OUT_CH);
        $readmemh("conv1_b.mem", conv1_b);

        $display("[INFO] Loading Conv2 weights (conv2_w.mem) — %0d entries ...",
                 CONV2_OUT_CH * CONV2_IN_CH * CONV2_KERNEL * CONV2_KERNEL);
        $readmemh("conv2_w.mem", conv2_w);

        $display("[INFO] Loading Conv2 biases (conv2_b.mem) — %0d entries ...",
                 CONV2_OUT_CH);
        $readmemh("conv2_b.mem", conv2_b);

        // ---- Load FC biases (weights loaded internally by layer_seq) ----
        $display("[INFO] Loading FC1 biases (fc1_b.mem) — %0d biases ...", FC1_OUT);
        $readmemh("fc1_b.mem", fc1_b);

        $display("[INFO] Loading FC2 biases (fc2_b.mem) — %0d biases ...", FC2_OUT);
        $readmemh("fc2_b.mem", fc2_b);

        // ---- Load input & label ----
        $display("[INFO] Loading input data (data_in.mem) — %0d pixels (28×28) ...",
                 INPUT_H * INPUT_W);
        $readmemh("data_in.mem", data_in);

        $display("[INFO] Loading expected label (expected_label.mem) ...");
        $readmemh("expected_label.mem", expected_label_arr);
        expected_label = expected_label_arr[0];
        $display("[INFO] Expected label: %0d\n", expected_label);

        // ---- Reset ----
        rstn = 1'b0;
        #(CLK_PERIOD_NS * 2);
        rstn = 1'b1;
        reset_cycle = cycle_count;
        $display("[INFO] Reset released at %0t ns (cycle %0d). Inference running ...\n", $time, reset_cycle);

        // ---- Wait for inference ----
        #(SIM_DURATION_NS);

        // ---- Results ----
        $display("\n");
        $display("############################################################");
        $display("#         2D CNN INFERENCE COMPLETE - RESULTS              #");
        $display("############################################################\n");

        display_all_outputs;
        find_predicted_digit;

        $display("");
        $display("  >>> DETECTED DIGIT: %0d <<<", detected_digit);
        $display("  >>> Confidence (raw Q16.16 logit): %0d <<<", max_val);
        $display("");
        $display("  --- EXPECTED DIGIT: %0d ---", expected_label);
        $display("");
        if (detected_digit == expected_label)
            $display("  *** RESULT: PASS ***");
        else
            $display("  *** RESULT: FAIL — Expected %0d but got %0d ***",
                     expected_label, detected_digit);
        $display("");

        // ---- Cycle breakdown ----
        $display("============================================================");
        $display("  CYCLE BREAKDOWN");
        $display("============================================================");
        $display("  Conv1+Pool1   done at cycle: %0d", conv1_pool1_cycle);
        $display("  Conv2+Pool2   done at cycle: %0d", conv2_pool2_cycle);
        $display("  FC1           done at cycle: %0d", fc1_cycle);
        $display("  FC2           done at cycle: %0d", fc2_cycle);
        $display("  TOTAL inference cycles: %0d", fc2_cycle - reset_cycle);
        $display("============================================================\n");

        #(CLK_PERIOD_NS * 2);
        $finish;
    end

    // ---- Monitor layer done signals ----
    always @(posedge dut.pool1_done) begin
        conv1_pool1_cycle = cycle_count;
        $display("[INFO] Conv1+Pool1 DONE at %0t ns (cycle %0d).", $time, conv1_pool1_cycle);
    end
    always @(posedge dut.pool2_done) begin
        conv2_pool2_cycle = cycle_count;
        $display("[INFO] Conv2+Pool2 DONE at %0t ns (cycle %0d).", $time, conv2_pool2_cycle);
    end
    always @(posedge dut.fc1_done) begin
        if (!fc1_done_seen) begin
            fc1_done_seen = 1;
            fc1_cycle = cycle_count;
            $display("[INFO] FC1 DONE at %0t ns (cycle %0d).", $time, fc1_cycle);
        end
    end
    always @(posedge dut.u_fc2.counter_donestatus) begin
        if (!fc2_done_seen) begin
            fc2_done_seen = 1;
            fc2_cycle = cycle_count;
            $display("[INFO] FC2 DONE at %0t ns (cycle %0d).", $time, fc2_cycle);
        end
    end

endmodule

